"""Add camera

Revision ID: 4212436d2fca
Revises: ab00dadcafca
Create Date: 2026-02-05 13:15:24.753452

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4212436d2fca'
down_revision: Union[str, Sequence[str], None] = 'ab00dadcafca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cameras',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_ip', sa.String(length=50), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('camera_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('user_logs', sa.Column('camera_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'user_logs', 'cameras', ['camera_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_logs', type_='foreignkey')
    op.drop_column('user_logs', 'camera_id')
    op.drop_table('cameras')
    # ### end Alembic commands ###
